export const types = {
    // Sync
    AUTHENTICATE: 'AUTHENTICATE',
    LOGOUT: 'LOGOUT',
    SIGNUP: 'SIGNUP',
    LOGIN_DEMO: 'LOGIN_DEMO',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',

    // Async
    LOGIN_ASYNC: 'LOGIN_ASYNC',
    LOGIN_WITH_TOKEN_ASYNC: 'LOGIN_WITH_TOKEN_ASYNC',
    SIGNUP_ASYNC: 'SIGNUP_ASYNC',
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    LOGOUT_ASYNC: 'LOGOUT_ASYNC',
    GET_USERDATA_ASYNC: 'GET_USERDATA_ASYNC',
    REFRESH_TOKENS_ASYNC: 'REFRESH_TOKENS_ASYNC',
};
