export const lastGameData = {
    assists: 8,
    bestMultikill: 'Rampage',
    bots: false,
    customMode: false,
    deaths: 0,
    denies: 1,
    gpm: 0,
    kills: 15,
    lastHits: 4,
    matchId: '5085254907',
    maximumKillStreak: 15,
    multikillsAmount: 7,
    party: null,
    playerHero: 'furion',
    playerInventory: [
        'item_slippers',
        'item_ring_of_protection',
        'item_blight_stone',
        'item_helm_of_iron_will',
        'item_mithril_hammer',
        'item_gem',
    ],
    playerSteamId: '76561198143141868',
    playerTeam: 'radiant',
    roster: {
        radiant: [],
        dire: [],
    },
    skillBuild: [
        'spectre_spectral_dagger',
        'spectre_spectral_dagger',
        'spectre_desolate',
        'spectre_spectral_dagger',
        'spectre_dispersion',
        'spectre_spectral_dagger',
        'spectre_reality',
        'spectre_haunt',
    ],
    smokesUsed: 0,
    victory: false,
    wardsPlaced: 0,
    xpm: 0,
};

export const extendedGameData = {
    result: {
        radiant_win: false,
        duration: 1325,
        pre_game_duration: 60,
        start_time: 1571943302,
        match_id: 5083788844,
        match_seq_num: 4265204205,
        tower_status_radiant: 4,
        tower_status_dire: 1974,
        barracks_status_radiant: 3,
        barracks_status_dire: 63,
        cluster: 133,
        first_blood_time: 28,
        lobby_type: 0,
        human_players: 10,
        leagueid: 0,
        positive_votes: 0,
        negative_votes: 0,
        game_mode: 23,
        flags: 0,
        engine: 1,
        radiant_score: 15,
        dire_score: 41,
        picks_bans: [
            {
                is_pick: false,
                hero_id: 53,
                team: 0,
                order: 0,
            },
        ],
        players: [
            {
                account_id: 133648173,
                player_slot: 0,
                hero_id: 104,
                item_0: 63,
                item_1: 168,
                item_2: 1,
                item_3: 182,
                item_4: 247,
                item_5: 127,
                backpack_0: 216,
                backpack_1: 0,
                backpack_2: 0,
                kills: 6,
                deaths: 8,
                assists: 4,
                leaver_status: 0,
                last_hits: 44,
                denies: 0,
                gold_per_min: 665,
                xp_per_min: 1250,
                level: 24,
                hero_damage: 14762,
                tower_damage: 207,
                hero_healing: 180,
                gold: 843,
                gold_spent: 14540,
                scaled_hero_damage: 8970,
                scaled_tower_damage: 203,
                scaled_hero_healing: 215,
                ability_upgrades: [
                    {
                        ability: 5595,
                        time: 140,
                        level: 1,
                    },
                ],
            },
        ],
    },
};
