export const types = {
    // Sync
    EMIT_ERROR: 'EMIT_ERROR',
    FILL_LEFT_SIDE: 'FILL_LEFT_SIDE',
    FILL_RIGHT_SIDE: 'FILL_RIGHT_SIDE',
    FILL_LEFT_SIDE_PROPS: 'FILL_LEFT_SIDE_PROPS',
    FILL_RIGHT_SIDE_PROPS: 'FILL_RIGHT_SIDE_PROPS',
};
